name: Building in java environment
run-name: ${{ github.actor }} is building main branch

on:
  push:
    branches:
      - main

jobs:
  build-main-branch:
    runs-on: ubuntu-latest
    environment: Default environment
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Publish parent pom as package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy -DskipSpringBootMavenRepackage \
            -DskipUnitTests \
            -DskipIntegrationTests \
            -DskipDependencyCheckAnalysis