on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${secrets.NVD_API_KEY}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Validate pull request with Maven
        run: mvn --batch-mode verify -Ddependency-check-maven.nvdApiKey="${NVD_API_KEY}"
