on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Validate pull request with Maven
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn --batch-mode verify -Ddependency-check-maven.nvdApiKey="$NVD_API_KEY"
